title: ng-openapi-gen
description: OpenAPI 3.0 & 3.1 code generator for Angular
theme: just-the-docs

url: https://czemar.github.io/ng-openapi-gen

aux_links:
  "ng-openapi-gen on GitHub":
    - "https://github.com/czemar/ng-openapi-gen"

aux_links_new_tab: true

search_enabled: true

heading_anchors: true

footer_content: "Copyright &copy; 2017 Social Trade Organisation. Distributed under the MIT license."

mermaid:
  version: "11.4.1"

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  note:
    title: Note
    color: purple
  tip:
    title: Tip
    color: green
  warning:
    title: Warning
    color: red

collections:
  docs:
    permalink: "/:collection/:path"
    output: true

just_the_docs:
  collections:
    docs:
      name: Documentation
